### ISSUE TITLE
rules error

### ISSUE THREAD

**Issue by arun81** [gazwald/nginx_waf#1]
Hi 
Thanks for your project

I am getting the following error while running image compiled using Dockerfile .

Please see screenshot attached

Please help what we are doing wrong .

Thanks
![nginx-waf-error-while-running-image](https://user-images.githubusercontent.com/13440263/43908153-c8ad4cc6-9be6-11e8-9061-416e65de0c75.png)

**Comment by arun81** [comment]
Now GETTING BELOW ERROR

$ docker run -p 80:80 cd84a008eac3
/bin/sh: line 0: [: missing `]'
[node1] (local) root@192.168.0.63 ~/nginx_waf

**Comment by gazwald** [comment]
Hi @arun81 

Apologies for not noticing you raised an issue sooner. Haven't been monitoring GitHub as much as I would have liked.

Anyway - that issue should be solved now.
